FROM gitnotifier/ruby:2.4.0

# Set proper locale
ENV APP_ENV=development \
APP_CONFIG_GITHUB_CLIENT_ID=someid \
APP_CONFIG_GITHUB_CLIENT_SECRET=somesecret \

APP_CONFIG_REDIS_HOST=localhost \
APP_CONFIG_REDIS_PORT=6379 \
APP_CONFIG_REDIS_DB=1 \
APP_CONFIG_REDIS_NAMESPACE=ghntfr \

APP_CONFIG_STATSD_HOST=localhost \
APP_CONFIG_STATSD_PORT=8125 \

APP_CONFIG_DOMAIN=gitnotifier.local \

APP_CONFIG_SECRET=somesecret \

APP_CONFIG_DEPLOY_ID=1 \

APP_CONFIG_EMAIL_DEV_ON_SIGNUP=false \
APP_CONFIG_DEV_EMAIL_ADDRESS=some@email.com

EXPOSE 9292

ENTRYPOINT [ "/usr/src/app/docker/puma/entrypoint.sh" ]
